### ISSUE TITLE
Adding <title> on pjax-templates seems not working properly

### ISSUE THREAD

**Issue by jorditost** [chrisguitarguy/pjaxy#3]
Adding a _<title>_ tag or attribute _data-title_ on the pjax-templates seems not working.

I think, the problem is in the function:

``` php
get_pjaxy_page_info();
```

There an object is created with _body_class_ and _page_title_ info, and page_title has value _wp_title();_

``` php
$info = array(
    'body_class'    => join( ' ', get_body_class( 'pjax-loaded' ) ),
    'page_title'    => wp_title( '', false ),
);
```

That vars are used after inside pjaxy.js, and _page_title_ is overwriting the value set inside the tag title in our template file.

``` javascript
jQuery('body').attr('class', pjaxy_page_info.body_class);
jQuery('head title').html(pjaxy_page_info.page_title);
```

I could solve it by commenting this second line.

**Comment by chrisguitarguy** [comment]
That's done on purpose.  Ideally you only load a small portion of the page, which doesn't included the <head> section. So, when the load is completed, the action bound to `pjax:end` replaces the title.

The biggest thing this library does is provide a mechanism for loading partial pages (eg. `pjaxy_find_template` and the respective template include filters).  If there's issues with the JS, i'd suggest dequeuing the pjaxy.js and rolling your own:

```
<?php
add_action('wp_enqueue_scripts', function() {
    wp_dequeue_script('pjaxy-core');
    // enqueue your script here
});
```

**Comment by jorditost** [comment]
Hi Chris, thanks for your reply.

I understand. What I've seen, is that PJAX also changes the title taking it from the "small portion" of the page. For example, in my _"pjax-templates/page.php"_ I have the following:

PJAX is taking the value of the title tag, and replacing it inside its success callback (_jquery.pjax.js_, line 218):

``` javascript
if (container.title) document.title = container.title;
```

and PJAXY overwrites this value inside _pjaxy.js_ with the `pjaxy_page_info.page_title` set in `get in get_pjaxy_page_info()` in _pjax.php_.
